default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5433

development:
  <<: *default
  database: airbnb_development
  username: airbnb
  password: "password"

test:
  <<: *default
  database: airbnb_test
  username: airbnb
  password: "password"

production:
  <<: *default
  database: airbnb_production
  username: airbnb
  password: "password"
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
  port: <%= ENV['PRODUCTION_DB_PORT'] %>
